apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-preview-spec-add-task-query

resources:
  - ../../base

images:
  - name: PLACEHOLDER_IMAGE
    newName: 947810884862.dkr.ecr.us-east-1.amazonaws.com/task-manager
    newTag: "spec-add-task-query-d574407"
