apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task

resources:
  - ../../base

images:
  - name: PLACEHOLDER_IMAGE
    newName: PLACEHOLDER_IMAGE
    newTag: "latest"
patches:
  - patch: |
      - op: replace
        path: /spec/rules/0/host
        value: task-manager-dev.softwareengineer.cloud
    target:
      kind: Ingress
      name: task-manager
