apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: controlador

resources:
  - ../../base

images:
  - name: PLACEHOLDER_IMAGE
    newName: 991192677553.dkr.ecr.us-east-1.amazonaws.com/controlador
    newTag: "1.0.0"
